
export const SET_LOADING = 'SET_LOADING';
export const SET_TAG_FILTER = 'SET_TAG_FILTER';
export const SET_REFRESH = 'SET_REFRESH';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FETCH_USER = 'AUTH_FETCH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';

export const OPEN_COMPOSE_MODAL = 'OPEN_COMPOSE_MODAL';
export const CLOSE_COMPOSE_MODAL = 'CLOSE_COMPOSE_MODAL';