
export const SET_LOADING = 'SET_LOADING';
export const SET_TAG_FILTER = 'SET_TAG_FILTER';
export const SET_REFRESH = 'SET_REFRESH';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FETCH_USER = 'AUTH_FETCH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
// export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';

export const FETCH_USER_ARTICLES = 'FETCH_USER_ARTICLES';
export const FETCH_USER_ARTICLES_FEED = 'FETCH_USER_ARTICLES_FEED';
export const FETCH_NEXT_USER_ARTICLES_FEED = 'FETCH_NEXT_USER_ARTICLES_FEED';
export const FETCH_USER_FAVORITED_ARTICLES = 'FETCH_USER_FAVORITED_ARTICLES';

export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_NEXT_ARTICLES = 'FETCH_NEXT_ARTICLES';
// export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE';
export const FETCH_ARTICLE_COMMENTS = 'FETCH_ARTICLE_COMMENTS';
// export const POST_ARTICLE_COMMENT = 'POST_ARTICLE_COMMENT';

export const FETCH_TAGS = 'FETCH_TAGS';

export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const OPEN_COMPOSE_MODAL = 'OPEN_COMPOSE_MODAL';
export const CLOSE_COMPOSE_MODAL = 'CLOSE_COMPOSE_MODAL';

export const DELETE_COMMENT = 'DELETE_COMMENT';