
export const SET_LOADING = 'SET_LOADING';
export const SET_TAG_FILTER = 'SET_TAG_FILTER';
export const SET_REFRESH = 'SET_REFRESH';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FETCH_USER = 'AUTH_FETCH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
// export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';

export const FETCH_USER_ARTICLES = 'FETCH_USER_ARTICLES';
export const FETCH_USER_FAVORITED_ARTICLES = 'FETCH_USER_FAVORITED_ARTICLES';

export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
// export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE';
export const FETCH_ARTICLE_COMMENTS = 'FETCH_ARTICLE_COMMENTS';
// export const POST_ARTICLE_COMMENT = 'POST_ARTICLE_COMMENT';

export const FETCH_TAGS = 'FETCH_TAGS';